spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: BackEndQuiz
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - profile
              - email
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  task:
    scheduling:
      pool:
        size: 2
openai:
  api-key: ${OPENAI_API_KEY}
  url: ${OPENAI_URL}
  model: gpt-4o-mini

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${TOKEN_EXP}
